# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36a2a56007e62588fa78eeb244e6829c2b074dc34d9d4cfaa8e90cd3658923f8d5b4bb3ae02c1c0943c0a76108e95958b1b79595da5a6a00bcd9368dfc919307

test:
  secret_key_base: 856aebb11688c2d2f7279ed02dd8e19dfb10f579870eb5adf494fa4f33ae5a949f7a48aff6405d1fcd292bd5397afc774e89536884af965f4a6f6ca394075467

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
